artifact_uri: file:D:/Kuliah/Semester 7/Asah/Tugas Project/SMSML_Rizki-Muhammad-Syamsi/Membangun_model/RizkiMSyamsi/SMSML_Rizki-Muhammad-Syamsi.mlflow/430436306747384856/39e96723d87f47c59825b45040c210ed/artifacts
end_time: 1764820333738
entry_point_name: ''
experiment_id: '430436306747384856'
lifecycle_stage: active
run_id: 39e96723d87f47c59825b45040c210ed
run_name: Ridge Regression - GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1764820326287
status: 3
tags: []
user_id: RizkiMSyamsi
