artifact_location: file:D:/Kuliah/Semester 7/Asah/Tugas Project/SMSML_Rizki-Muhammad-Syamsi/Membangun_model/RizkiMSyamsi/SMSML_Rizki-Muhammad-Syamsi.mlflow/0
creation_time: 1764653913412
experiment_id: '0'
last_update_time: 1764653913412
lifecycle_stage: active
name: Default
